<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>TechTicketPOC.Entities</AssemblyName>
    <RootNamespace>TechTicketPOC.Entities</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TechTicketPOC.Common\TechTicketPOC.Common.csproj" />
  </ItemGroup>
</Project>